version: "3.9"
services:
  bioc:
    container_name: grocamora_rstudio_custom
    image: "grocamora-rstudio:v1.4"
    ports:
      - "8097:8787"
    environment:
      - PASSWORD=bioc
      - ROOT=TRUE
    volumes:
      - ~/.:/home/grocamora/
