version: "3.9"
services:
  bioc:
    container_name: grocamora-rstudio
    image: "grocamora-rstudio:v2.0"
    ports:
      - "8097:8787"
    environment:
      - PASSWORD=bioc
      - ROOT=TRUE
    volumes:
      - ~/.:/home/grocamora
